site_name: Docs Flutter ERP

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: 

extra_css:
  - stylesheets/extra.css   

nav:
  - Primeiros passos: 
    - Introdução: primeiros_passos/intro.md
    - Arquitetura & organização de projeto:  primeiros_passos/arq_org.md
    - Introdução sobre modulos:  primeiros_passos/intro_modulos.md  # Faz uma introdução sobre os modulos, oq sao, pra q servem, etc. Fala sobre a diferenção entre os tipos de modulos ( modulo system e modulos genericos ) 
    - Criar modulo genérico: primeiros_passos/criar_modulo.md
    - Criar modulo system: primeiros_passos/null.md  # talvez nao precisa ter esse topico, afinal o modulo index é algo fixo que nao vai precisar ficar sendo criado diversas vezes igual o modulo generico
    - Montar uma tela: primeiros_passos/montar_tela.md
  - Widgets: 
    - Intr0dução: widgets/intro.md

theme:
  name: null
  custom_dir: mkdocs-material/material
  features:
    - content.code.annotate 

   

  palette:
    primary: teal

  # features:
  #   - navigation.expand

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo